columnSuffix: null
handle: headerBgColor
instructions: null
name: 'Header Bg Color ?'
searchable: false
settings:
  allowCustomColors: false
  palette:
    -
      __assoc__:
        -
          - color
          - '#ffe0e0'
        -
          - label
          - ''
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - color
          - '#d6d1ff'
        -
          - label
          - ''
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Color
